"""Solution table and Problems->function_name, peremeters, return type field

Revision ID: f092392c86e0
Revises: d41e75bac479
Create Date: 2025-11-09 13:35:02.791232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f092392c86e0'
down_revision: Union[str, Sequence[str], None] = 'd41e75bac479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('function_name', sa.String(length=100), nullable=True))
    op.add_column('problems', sa.Column('parameters', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('return_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'return_type')
    op.drop_column('problems', 'parameters')
    op.drop_column('problems', 'function_name')
    # ### end Alembic commands ###
